# Regras de Análise Estática para o Pacote Dart 3 Puro (Cici)
linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_string_interpolations: true
